image: registry.pf9.io/gitpod/workspace-images@sha256:9bb9abd378dc80ad26a3605ba584efa4de30f621fb24ee70b0b34b5852c7b938
ports:
  - port: 8080
    onOpen: open-preview
checkoutLocation: "go/src/github.com/demo-apps/go-gin-app"
workspaceLocation: "go/src/github.com/demo-apps/go-gin-app"
tasks:
  - init: >
      go get -v ./... &&
      go build -o app
    command: >
      ./app
github:
    prebuilds:
        pullRequestsFromForks: true
